package chatmodule;


/**
* chatmodule/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 00 h 25 CET
*/

public final class Client implements org.omg.CORBA.portable.IDLEntity
{
  public String nickName = null;

  public Client ()
  {
  } // ctor

  public Client (String _nickName)
  {
    nickName = _nickName;
  } // ctor

} // class Client
