package chatmodule;


/**
* chatmodule/DialogueOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 00 h 25 CET
*/

public interface DialogueOperations 
{
  chatmodule.Dialog dialogue ();
  void dialogue (chatmodule.Dialog newDialogue);
  chatmodule.Client[] getClients ();
  void sendMessage (String to, String message);
  chatmodule.Message[] getMessages (String pseudo);
} // interface DialogueOperations
