package chatmodule;


/**
* chatmodule/Dialog.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 00 h 25 CET
*/

public final class Dialog implements org.omg.CORBA.portable.IDLEntity
{
  public chatmodule.Client client = null;
  public chatmodule.Message messagesClient[] = null;

  public Dialog ()
  {
  } // ctor

  public Dialog (chatmodule.Client _client, chatmodule.Message[] _messagesClient)
  {
    client = _client;
    messagesClient = _messagesClient;
  } // ctor

} // class Dialog
