package chatmodule;

/**
* chatmodule/DialogHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 00 h 25 CET
*/

public final class DialogHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Dialog value = null;

  public DialogHolder ()
  {
  }

  public DialogHolder (chatmodule.Dialog initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.DialogHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.DialogHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.DialogHelper.type ();
  }

}
