package chatmodule;


/**
* chatmodule/DialogHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 00 h 25 CET
*/

abstract public class DialogHelper
{
  private static String  _id = "IDL:chatmodule/Dialog:1.0";

  public static void insert (org.omg.CORBA.Any a, chatmodule.Dialog that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static chatmodule.Dialog extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = chatmodule.ClientHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "client",
            _tcOf_members0,
            null);
          _tcOf_members0 = chatmodule.MessageHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (chatmodule.MessagesHelper.id (), "Messages", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "messagesClient",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (chatmodule.DialogHelper.id (), "Dialog", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static chatmodule.Dialog read (org.omg.CORBA.portable.InputStream istream)
  {
    chatmodule.Dialog value = new chatmodule.Dialog ();
    value.client = chatmodule.ClientHelper.read (istream);
    value.messagesClient = chatmodule.MessagesHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, chatmodule.Dialog value)
  {
    chatmodule.ClientHelper.write (ostream, value.client);
    chatmodule.MessagesHelper.write (ostream, value.messagesClient);
  }

}
