package chatmodule;


/**
* chatmodule/MessagesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from chat.idl
* lundi 25 janvier 2016 00 h 25 CET
*/

public final class MessagesHolder implements org.omg.CORBA.portable.Streamable
{
  public chatmodule.Message value[] = null;

  public MessagesHolder ()
  {
  }

  public MessagesHolder (chatmodule.Message[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = chatmodule.MessagesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    chatmodule.MessagesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return chatmodule.MessagesHelper.type ();
  }

}
